pipeline { 
    agent any 
    
	tools {
		maven 'maven-3.9.11' //Check the version in Jenkins Global Tool Configuration
		
	}

	environment {
		PROJECT_FOLDER = "Selenium-Web-Automation-Framework" // ${PROJECT_FOLDER}
		COMPOSE_PATH = "${WORKSPACE}/${PROJECT_FOLDER}/docker" // 🔁 Adjust if compose file is elsewhere
        SELENIUM_GRID = "true"
        GitHub_REPO = "https://github.com/tonysaha007/WebAutomationProject.git"
        
       	// https://github.com/repo.git // ${GitHub_REPO}
		//	│
		//	├── Project Folder Name // ${PROJECT_FOLDER}
		//	│   ├── pom.xml
		//
	} 
	    
    stages {

		stage('Environment Setup') {

		    	steps {
	                script {
						echo "checking installed versions..."
						bat 'docker --version'
						bat 'docker compose version'
						bat 'mvn -version'
						bat 'java -version'
	                    bat "docker compose -f ${COMPOSE_PATH}\\docker-compose.yml up -d"
	                    echo "Waiting for Selenium Grid to be ready..."
	                    sleep 10 // Add a wait if needed
	                    echo "Environment setup complete. COMPOSE_PATH set to ${COMPOSE_PATH}"
	                }
            	}
	    }
	    	
        stage('Checkout Repository') {
            steps {
                git branch: 'master', url: "${GitHub_REPO}" // 🔁 Adjust per git repo
            }
        }

        stage('Build') {
            steps {
				dir("${PROJECT_FOLDER}") { // 🔁 Adjust per git repo
					bat 'mvn clean install -f pom.xml' 
				}
                
            }
        }

        stage('Test') {
            steps {
				dir("${PROJECT_FOLDER}") { // 🔁 Adjust per git repo
					bat 'mvn test -f pom.xml' 
				}
                
            }
        }
		stage('Stop Selenium Grid') {
		            steps {
		                script {
		                    echo "Stopping Selenium Grid and removing containers..."
		                    bat "docker compose -f ${COMPOSE_PATH}\\docker-compose.yml down" // Stop and remove containers
		                }
		            }
		 }
        stage('Publish Reports') {
            steps {
                publishHTML(target: [
                    reportDir: "${PROJECT_FOLDER}/src/test/resources/ExtentReport",  //🔁 Adjust as per folder
                    reportFiles: 'ExtentReport.html',  
                    reportName: 'Extent Spark Report'
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: "**/${PROJECT_FOLDER}/src/test/resources/ExtentReport/*.html", fingerprint: true
            junit "${PROJECT_FOLDER}/target/surefire-reports/*.xml"
            echo 'artifacts have been archived and test results published.'
        }
        
        success {
            echo 'The build was successful!'
			emailext(
			    to: 'tony.ez007@gmail.com',
			    subject: "Build Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
			    body: """
			    <html>
 				<body style="font-family: Arial, Helvetica, sans-serif; background-color:#f4f6f8; padding:20px;">
			            <table align="center" width="600"
						cellpadding="0" cellspacing="0"
						style="background:#ffffff;
						border:1px solid #dcdcdc;
						border-radius:8px;
						box-shadow:0 2px 6px rgba(0,0,0,0.08);">
			            <tr>
			                <td style="padding:20px; text-align:center; background:#2ecc71; color:#ffffff; border-radius:8px 8px 0 0;">
			                    <h2>Build Successful</h2>
			                </td>
			            </tr>
			            
			            <tr>
			                <td style="padding:20px;">
			                    <p>Hello <b>Automation Team</b>,</p>
			
			                    <p>The latest Jenkins build #${env.BUILD_NUMBER} has completed successfully.</p>
			
			                    <table width="100%" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
			                        <tr>
			                            <td><b>Project Name</b></td>
			                            <td>${env.JOB_NAME}</td>
			                        </tr>
			                        <tr>
			                            <td><b>Build Number</b></td>
			                            <td>#${env.BUILD_NUMBER}</td>
			                        </tr>
			                        <tr>
			                            <td><b>Status</b></td>
			                            <td style="color:#2ecc71;"><b>SUCCESS</b></td>
			                        </tr>
			                        <tr>
			                            <td><b>Build URL</b></td>
			                            <td>
			                                <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
			                            </td>
			                        </tr>
			                    </table>
			
			                    <p style="margin-top:20px;">
			                        <b>Extent Report:</b><br/>
			                        <a href="http://localhost:8080/job/${env.JOB_NAME}/${env.BUILD_NUMBER}/artifact/${PROJECT_FOLDER}/src/test/resources/ExtentReport/ExtentReport.html"> 
			                            Click here to view report
			                        </a>
			                    </p>
			
			                    <p style="margin-top:30px;">
			                        Best regards,<br/>
			                        <b>Web Automation Team</b>
			                    </p>
			                </td>
			            </tr>
			        </table>
			    </body>
			    </html>
			    """,
			    mimeType: 'text/html',
			    attachLog: true,
			    attachmentsPattern: "${PROJECT_FOLDER}/logs/app.log" // 🔁 Adjust path as needed
			)
        }
        
        failure {
            echo 'The build failed.'
            
           emailext(
					
					to: 'tony.ez007@gmail.com',
				    subject: "Build Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
				    body: """
					<html>
					  <body style="font-family: Arial, Helvetica, sans-serif; background-color:#f4f6f8; padding:20px;">
					    <table align="center" width="600"
					        cellpadding="0" cellspacing="0"
					        style="background:#ffffff;
					        border:1px solid #dcdcdc;
					        border-radius:8px;
					        box-shadow:0 2px 6px rgba(0,0,0,0.08);">
					        
					      <tr>
					        <td style="padding:20px; text-align:center; background:#e74c3c; color:#ffffff; border-radius:8px 8px 0 0;">
					          <h2>Build Failed</h2>
					        </td>
					      </tr>
					
					      <tr>
					        <td style="padding:20px;">
					          <p>Hello <b>Automation Team</b>,</p>
					
					          <p>The latest Jenkins build #${env.BUILD_NUMBER} has <b>FAILED</b>. Please check the logs and take necessary action.</p>
					
					          <table width="100%" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
					            <tr>
					              <td><b>Project Name</b></td>
					              <td>${env.JOB_NAME}</td>
					            </tr>
					            <tr>
					              <td><b>Build Number</b></td>
					              <td>#${env.BUILD_NUMBER}</td>
					            </tr>
					            <tr>
					              <td><b>Status</b></td>
					              <td style="color:#e74c3c;"><b>FAILURE</b></td>
					            </tr>
					            <tr>
					              <td><b>Build URL</b></td>
					              <td>
					                <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
					              </td>
					            </tr>
					          </table>
					
					          <p style="margin-top:20px;">
					            <b>Console Output:</b><br/>
					            <a href="${env.BUILD_URL}console">
					              Click here to view console log
					            </a>
					          </p>
					
					          <p style="margin-top:20px;">
					            <b>Extent Report (if generated):</b><br/>
					            <a href="http://localhost:8080/job/${env.JOB_NAME}/${env.BUILD_NUMBER}/artifact/${PROJECT_FOLDER}/src/test/resources/ExtentReport/ExtentReport.html">
					              Click here to view report
					            </a>
					          </p>
					
					          <p style="margin-top:30px;">
					            Best regards,<br/>
					            <b>Web Automation Team</b>
					          </p>
					        </td>
					      </tr>
					    </table>
					  </body>
				</html>    
			    """,
			    mimeType: 'text/html',
	    		attachLog: true,
	    		attachmentsPattern: "${PROJECT_FOLDER}/logs/error.log" 
					
		   ) 
        }
    }
}